### ISSUE TITLE
No rule to make target?

### ISSUE THREAD

**Issue by marvin1099** [stoth68000/sc0710#2]
I hope this is an easy fix wold be nice if i cold use my elgato 4k60mk2 on my linux ubuntu system (yes i know this isn't especially written for ubuntu but hope dies last).
Thanks for future help.

Commands:
git clone https://github.com/stoth68000/sc0710.git
cd sc0710
sudo make

Outputs:
make -C /lib/modules/5.11.0-17-generic/build M= modules
make[1]: Entering directory '/usr/src/linux-headers-5.11.0-17-generic'
make[2]: *** No rule to make target 'arch/x86/tools/relocs_32.c', needed by 'arch/x86/tools/relocs_32.o'.  Stop.
make[1]: *** [arch/x86/Makefile:210: archscripts] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.11.0-17-generic'
make: *** [Makefile:14: all] Error 2

**Comment by hutber** [comment]
If it helps at all:

```
hutber@hutber:/var/www/sc0710$ make
make -C /lib/modules/5.8.0-53-generic/build M=/var/www/sc0710 modules
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-53-generic'
  CC [M]  /var/www/sc0710/sc0710-cards.o
In file included from /var/www/sc0710/sc0710-cards.c:21:
/var/www/sc0710/sc0710.h:103:18: error: field ‘lastTime’ has incomplete type
  103 |  struct timespec lastTime;
      |                  ^~~~~~~~
make[2]: *** [scripts/Makefile.build:286: /var/www/sc0710/sc0710-cards.o] Error 1
make[1]: *** [Makefile:1777: /var/www/sc0710] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-53-generic'
make: *** [Makefile:14: all] Error 2
```

**Comment by marvin1099** [comment]
Thanks for trying to help. I don't know enough to get any Idea what the problem is based on this.

**Comment by stoth68000** [comment]
struct timespec has probably moved in the 5.8 kernel headers.
You probably need to go searching for where it's defined and include that in the sc0710.h headers.
All of my work is on 3.x kernels for Centos, I haven't tried using 4.x kernels or beyond.

**Comment by marvin1099** [comment]
You think i need to search where struct timespec is defined and include "sc0710.h".
Did i understand that correctly.
Right now i kind of busy but if i find some time i will try this thanks.

**Comment by nochristrequired** [comment]
I'm running into this issue as well with 5.12.2 on Gentoo with regards to timespec.
I'm going to dig around a bit this weekend and see if I can get it to compile.

Thank you for posting your work and I will follow up here with my findings.

*Edit* I have fixed the issue with timespec, however, I ran into other incompatibilities. One of them is the pci_dma issue as reported with 4.18 but it looks like there are a couple additional issues as well. I'll open a PR once I have sorted the fixes for 5.x.

**Comment by Sori-Xia** [comment]
First of all: thx for all your efforts!!!

So I included "include <linux/time.h>" to get timespec.
However I needed to change it to timespec64 (hopefully it was correct).

But it resulted in even more errors :) 

 /home/user/sc0710/sc0710-core.c: In function ‘sc0710_proc_create’: 
/home/user/sc0710/sc0710-core.c:339:44: error: passing argument 4 of ‘proc_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
339 |  pe = proc_create("sc0710", S_IRUGO, NULL, &sc0710_proc_fops);
struct file_operations *
In file included from /home/user/sc0710/sc0710.h:59,
from /home/user/sc0710/sc0710-core.c:21:
./include/linux/proc_fs.h:109:122: note: expected ‘const struct proc_ops *’ but argument is of type ‘struct file_operations *’
109 | struct proc_dir_entry *proc_create(const char *name, umode_t mode, struct proc_dir_entry *parent, const struct proc_ops *proc_ops);
/home/user/sc0710/sc0710-core.c:343:50: error: passing argument 4 of ‘proc_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
343 |  pe = proc_create("sc0710-state", S_IRUGO, NULL, &sc0710_proc_state_fops);
struct file_operations *
In file included from /home/user/sc0710/sc0710.h:59,
from /home/user/sc0710/sc0710-core.c:21:
./include/linux/proc_fs.h:109:122: note: expected ‘const struct proc_ops *’ but argument is of type ‘struct file_operations *’
  109 | struct proc_dir_entry *proc_create(const char *name, umode_t mode, struct proc_dir_entry *parent, const struct proc_ops *proc_ops);
/home/user/sc0710/sc0710-core.c: In function ‘sc0710_initdev’:
/home/user/sc0710/sc0710-core.c:480:7: error: implicit declaration of function ‘pci_dma_supported’; did you mean ‘acpi_dma_supported’? [-Werror=implicit-function-declaration]
  480 |  if (!pci_dma_supported(pci_dev, 0xffffffff)) {
      |       ^~~~~~~~~~~~~~~~~
      |       acpi_dma_supported
/home/user/sc0710/sc0710-core.c:495:4: error: ‘IRQF_DISABLED’ undeclared (first use in this function); did you mean ‘UMH_DISABLED’?
  495 |    IRQF_DISABLED, dev->name, dev);
      |    ^~~~~~~~~~~~~
      |    UMH_DISABLED
/home/user/sc0710/sc0710-core.c:495:4: note: each undeclared identifier is reported only once for each function it appears in
cc1: some warnings being treated as errors

**Comment by thehonkinggoose** [comment]
Vincent made some progress on a patch at https://github.com/stoth68000/sc0710/issues/4 which is worth looking at.
