### ISSUE TITLE
Mk.1 support plans?

### ISSUE THREAD

**Issue by RiotArchiveProject** [stoth68000/sc0710#3]
This isn't an issue per se, I'm just curious how likely there will be research into the Mk.1 variant will be as I'm unfortunately the owner of one.  
I'm unaware of how great the differences are between them, I know there's a slight feature change but generally they support the same things, but because they're significantly different on the board it may be worth inquiring about this.

**Comment by stoth68000** [comment]
Thanks for reaching out.
Negative, I have no plans to look at the mk.1

**Comment by RiotArchiveProject** [comment]
Ah, no worries then. Thanks.
