### ISSUE TITLE
sc0710/sc0710.h:103:18: error: field ‘lastTime’ has incomplete type

### ISSUE THREAD

**Issue by tribbin** [stoth68000/sc0710#6]
What is the state of this project?

robin@debian:~/git/sc0710$ make
make -C /lib/modules/5.10.0-8-amd64/build M=/home/robin/git/sc0710 modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.0-8-amd64'
  CC [M]  /home/robin/git/sc0710/sc0710-cards.o
In file included from /home/robin/git/sc0710/sc0710-cards.c:21:
/home/robin/git/sc0710/sc0710.h:103:18: error: field ‘lastTime’ has incomplete type
  103 |  struct timespec lastTime;
      |                  ^~~~~~~~
make[3]: *** [/usr/src/linux-headers-5.10.0-8-common/scripts/Makefile.build:285: /home/robin/git/sc0710/sc0710-cards.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.10.0-8-common/Makefile:1845: /home/robin/git/sc0710] Error 2
make[1]: *** [/usr/src/linux-headers-5.10.0-8-common/Makefile:185: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.0-8-amd64'
make: *** [Makefile:14: all] Error 2

**Comment by stoth68000** [comment]
It's a pet project that was developed on centos 7.6 using a 3.10 kernel.
At some point I'll spin up an Ubuntu 20.04 system and forward port it.

**Comment by stoth68000** [comment]
I'm planning to revisit the driver again short for some HDR related work.
If things go faster than anticipated then I'll forward port to ubuntu 20.04 also.

**Comment by StarWitch** [comment]
Also tried running this driver on the 5.13 kernels inside Ubuntu 21.10. It compiles and loads correctly with the patch @NogradThGin provided in #4, but fails to initialize the card itself with the DMA error seen in that issue. I'm not much of a driver developer myself, but I can help provide testing of patches if needed.

**Comment by NogradThGin** [comment]
Hello.
I dit not got so much time since my last try with the DMA. I will soon have a bit more time to investigate once again on this.
I'll try to keep the issue #4 updated.

**Comment by DeWolfRobin** [comment]
I have a solution that won't solve the whole thing, but at least this issue:
change line 103 from `struct timespec lastTime;` to `struct timespec64 lastTime;` and import `#include <linux/time.h>` at the top.
